"""convert strain name assoc to class

Revision ID: 4513677bfb4e
Revises: f05fc486a0fd
Create Date: 2020-04-05 14:39:09.825870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4513677bfb4e'
down_revision = 'f05fc486a0fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
